answers:
  start_without_group: "Привет \U0001F44B Напиши название учебной группы, чтобы узнать её расписание. Например, МПГДбд-11 или ИСдо-11."
  start_with_group: "Привет \U0001F44B Напиши:\n\n\U0001F539 «1» или «Моё расписание», чтобы перейти к расписанию выбранной группы\n\n\U0001F539 «2» или «Изменить группу», чтобы поменять группу, расписание которой ты будешь получать"
  change_group: "Напиши название учебной группы \U0000270F Например, МПГДбд-11 или ИСдо-11."
  back: "Напиши:\n\n\U0001F539 «1» или «Моё расписание», чтобы перейти к расписанию выбранной группы\n\n\U0001F539 «2» или «Изменить группу», чтобы поменять группу, расписание которой ты будешь получать"
  info_without_group: "Напиши название учебной группы, чтобы узнать её расписание \U0000270F Например, МПГДбд-11 или ИСдо-11."
  info_with_group: "Напиши:\n\n\U0001F539 «3» или «Сегодня», чтобы получить расписание на сегодняшний день\n\n\U0001F539 «4» или «Завтра», чтобы узнать расписание на завтрашний день\n\n\U0001F539 «5» или «Текущая неделя», чтобы узнать расписание на текущую неделю\n\n\U0001F539 «6» или «Следующая неделя», чтобы узнать расписание на следующую неделю\n\n\U0001F539 «7» или «Назад», чтобы вернуться в главное меню"
  about_project: "Данный проект создан студентами университета и не имеет никакого отношения к администрации вуза.\n\nТехподдержка: @tmrrwnxtsn, @BossMouseFire\n\nМы во «ВКонтакте»: vk.com/scheduleofulstu"

additions:
  changes_in_kei_schedule: "Возможные изменения в расписании: https://vk.cc/bWfVyE"

errors:
  incorrect_input: "Возможно, название команды или группы написано неверно. Проверь правильность написания и повтори попытку \U0001F501"
  group_not_selected: "Группа не выбрана! Напиши название группы, чтобы узнать её расписание \U0000270F Например, МПГДбд-11 или ПИбд-21 (Название группы такое же, как и на сайте с расписанием)."
  curr_week_schedule_is_unavailable: "К сожалению, расписание на текущую неделю временно недоступно... Повтори попытку позже \U0001F501"
  next_week_schedule_is_unavailable: "К сожалению, расписание на следующую неделю временно недоступно... Повтори попытку позже \U0001F501"
  failed_to_update_group: "К сожалению, не удалось обновить учебную группу... Повтори попытку позже \U0001F501"
  server_error: "К сожалению, произошла ошибка при обращении к серверу... Повтори попытку позже \U0001F501"

stickers:
  to_express_gratitude: "CAACAgIAAxkBAAECxklhHgvLpAGNdaRjAAFqTL2JTRIjsO8AAjAAA8GcYAwvzt8TTApnnCAE"
  to_sticker: "CAACAgIAAxkBAAECxk1hHgx1s9L1UxravIy6l4qIYorFpQACJAADwZxgDEgkWrolDSiOIAQ"
  to_voice: "CAACAgIAAxkBAAECxk9hHgzS7Zjbo7dMLkcya2A7UBD-egACIwADwZxgDJDk7nBqLVflIAQ"
