without_slash:
  inline:
    first_lvl:
      groups:
        command: "Расписание групп"
        data: "groups"
      teachers:
        command: "Расписание учителей"
        data: "teachers"
    second_lvl:
      groups:
        schedule:
          command: "Моё расписание"
          data: "groups_schedule"
        change:
          command: "Изменить группу"
          data: "groups_change"
      teachers:
        schedule:
          command: "Моё расписание"
          data: "teachers_schedule"
        change:
          command: "Изменить учителя"
          data: "teachers_change"
      back:
        command: "Назад"
        data: "first_menu"
    third_lvl:
      commands:
        today: "Сегодня"
        tomorrow: "Завтра"
        curr_week: "Текущая неделя"
        next_week: "Следующая неделя"
      data:
        groups:
          today: "groups_schedule_today"
          tomorrow: "groups_schedule_tomorrow"
          curr_week: "groups_schedule_curr_week"
          next_week: "groups_schedule_next_week"
        teachers:
          today: "teachers_schedule_today"
          tomorrow: "teachers_schedule_tomorrow"
          curr_week: "teachers_schedule_curr_week"
          next_week: "teachers_schedule_next_week"
      back:
        command: "Назад"
        data:
          groups: "groups"
          teachers: "teachers"
  whole:
    go_to_schedule_menu:
      - "1"
    change_group:
      - "2"
    get_schedule_for_day:
      - "3"
      - "4"
      - "сегодня"
      - "завтра"
    get_schedule_for_week:
      - "5"
      - "6"
    back_to_start_menu:
      - "7"
  partial:
    go_to_schedule_menu:
      - "расписани"
      - "недел"
    get_schedule_for_week:
      - "текущая неделя"
      - "следующая неделя"
    change_group:
      - "изменить"
      - "поменять"
    back_to_start_menu:
      - "отмена"
      - "назад"
      - "вернуться"
    express_gratitude:
      - "спасиб"
      - "сенкс"
      - "благодар"
      - "спс"
      - "thanks"
with_slash:
  start: "start"
  help: "help"
  about_project: "about"